name: Build & Push Subscription 5

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: anandaacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME_SUB5 }}
          password: ${{ secrets.ACR_PASSWORD_SUB5 }}

      - run: |
          docker build . -t anandaacr.azurecr.io/ananda-mock-serv-01:${{ github.sha }}
          docker push anandaacr.azurecr.io/ananda-mock-serv-01:${{ github.sha }}